version: '3'

services:
  db:
    container_name: database
    image: postgres:15.3-alpine
    ports:
      - 5432:5432
    volumes:
      - ./.data/postgres/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres